<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ripcord.Domain\Ripcord.Domain.csproj" />
    <ProjectReference Include="..\Ripcord.Ports\Ripcord.Ports.csproj" />
  </ItemGroup>

</Project>
